### ISSUE TITLE
Git SVN

### ISSUE THREAD

**Issue by arthurgeron** [ghooks-org/ghooks#228]
I manage a SVN repository through git svn, would it work in that case as well?

**Comment by gtramontina** [comment]
Sorry for the late reply… It's been a long while since I dealt with git-svn, but as far as I remember, the hooks are different (not sure if all of them, or even if git-svn ends up triggering git's hooks)… anyway, this library sets up the hooks listed [here](https://github.com/ghooks-org/ghooks#all-documented-hooks-are-available). I'd suggest giving a try (if you haven't already 😄), but I wouldn't hold out much hope.

In fact, I am thinking about a new major version of ghooks (from the ground up) that could potentially address these things as it would approach git hooks differently. Can't promise anything yet, though…

**Comment by arthurgeron** [comment]
since you have to run first "git commit" and then "git svn dcommit" the hooks works on the first part, thank you anyway. I'm looking forward for that new major version! Thanks
